### ISSUE TITLE
Cho e hỏi về dự án cũ đã tích hợp framework này không support cho các bản Xcode mới nữa?

### ISSUE THREAD

**Issue by Sotatek-TrungNguyen** [dungntm58/iOSCore#1]
Em đang tiếp nhận lại dự án của anh có tích hợp framework này của anh. Có một vấn đề là khi nâng cấp Xcode lên thì không thể build được với Xcode mới nhất nữa Lỗi: Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler.

Em đã thử bỏ hết framework để cho luôn phần code Base và Request vào folder rồi chuyển vào project nhưng không thể tìm thấy file DataWorker đâu và phải phụ thuộc rất nhiều phần khác.

Cho em hỏi giải pháp để xử lý lỗi này. Hoặc anh có thể gửi code phần core này đề cho e build bản framework mới nhất này không.

Rất mong được anh giúp đỡ.

**Comment by dungntm58** [comment]
Sorry vì rep bạn muộn quá, hiện tại, các repo cũ thì mình cũng deprecate và tập trung hết vào repo này, repo này có nhiều thứ mới, ko phù hợp với project cũ đang chạy.
Lỗi này bạn thử clean project r build lại xem, vì swift 5.2 đã compatible với swift 5.1

**Comment by Sotatek-TrungNguyen** [comment]
Đã clean build thử rất nhiều lần vẫn không build được. Lỗi này ông ơi:
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2.2 compiler.

Theo ý ông là làm theo hướng pod repo mới này để fix à.
